#if 0
#elif defined(__arm64__) && __arm64__
// Generated by Apple Swift version 6.1.2 effective-5.10 (swiftlang-6.1.2.1.2 clang-1700.0.13.5)
#ifndef BCLRINGSDK_SWIFT_H
#define BCLRINGSDK_SWIFT_H
#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wgcc-compat"

#if !defined(__has_include)
# define __has_include(x) 0
#endif
#if !defined(__has_attribute)
# define __has_attribute(x) 0
#endif
#if !defined(__has_feature)
# define __has_feature(x) 0
#endif
#if !defined(__has_warning)
# define __has_warning(x) 0
#endif

#if __has_include(<swift/objc-prologue.h>)
# include <swift/objc-prologue.h>
#endif

#pragma clang diagnostic ignored "-Wauto-import"
#if defined(__OBJC__)
#include <Foundation/Foundation.h>
#endif
#if defined(__cplusplus)
#include <cstdint>
#include <cstddef>
#include <cstdbool>
#include <cstring>
#include <stdlib.h>
#include <new>
#include <type_traits>
#else
#include <stdint.h>
#include <stddef.h>
#include <stdbool.h>
#include <string.h>
#endif
#if defined(__cplusplus)
#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wnon-modular-include-in-framework-module"
#if defined(__arm64e__) && __has_include(<ptrauth.h>)
# include <ptrauth.h>
#else
#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wreserved-macro-identifier"
# ifndef __ptrauth_swift_value_witness_function_pointer
#  define __ptrauth_swift_value_witness_function_pointer(x)
# endif
# ifndef __ptrauth_swift_class_method_pointer
#  define __ptrauth_swift_class_method_pointer(x)
# endif
#pragma clang diagnostic pop
#endif
#pragma clang diagnostic pop
#endif

#if !defined(SWIFT_TYPEDEFS)
# define SWIFT_TYPEDEFS 1
# if __has_include(<uchar.h>)
#  include <uchar.h>
# elif !defined(__cplusplus)
typedef unsigned char char8_t;
typedef uint_least16_t char16_t;
typedef uint_least32_t char32_t;
# endif
typedef float swift_float2  __attribute__((__ext_vector_type__(2)));
typedef float swift_float3  __attribute__((__ext_vector_type__(3)));
typedef float swift_float4  __attribute__((__ext_vector_type__(4)));
typedef double swift_double2  __attribute__((__ext_vector_type__(2)));
typedef double swift_double3  __attribute__((__ext_vector_type__(3)));
typedef double swift_double4  __attribute__((__ext_vector_type__(4)));
typedef int swift_int2  __attribute__((__ext_vector_type__(2)));
typedef int swift_int3  __attribute__((__ext_vector_type__(3)));
typedef int swift_int4  __attribute__((__ext_vector_type__(4)));
typedef unsigned int swift_uint2  __attribute__((__ext_vector_type__(2)));
typedef unsigned int swift_uint3  __attribute__((__ext_vector_type__(3)));
typedef unsigned int swift_uint4  __attribute__((__ext_vector_type__(4)));
#endif

#if !defined(SWIFT_PASTE)
# define SWIFT_PASTE_HELPER(x, y) x##y
# define SWIFT_PASTE(x, y) SWIFT_PASTE_HELPER(x, y)
#endif
#if !defined(SWIFT_METATYPE)
# define SWIFT_METATYPE(X) Class
#endif
#if !defined(SWIFT_CLASS_PROPERTY)
# if __has_feature(objc_class_property)
#  define SWIFT_CLASS_PROPERTY(...) __VA_ARGS__
# else
#  define SWIFT_CLASS_PROPERTY(...) 
# endif
#endif
#if !defined(SWIFT_RUNTIME_NAME)
# if __has_attribute(objc_runtime_name)
#  define SWIFT_RUNTIME_NAME(X) __attribute__((objc_runtime_name(X)))
# else
#  define SWIFT_RUNTIME_NAME(X) 
# endif
#endif
#if !defined(SWIFT_COMPILE_NAME)
# if __has_attribute(swift_name)
#  define SWIFT_COMPILE_NAME(X) __attribute__((swift_name(X)))
# else
#  define SWIFT_COMPILE_NAME(X) 
# endif
#endif
#if !defined(SWIFT_METHOD_FAMILY)
# if __has_attribute(objc_method_family)
#  define SWIFT_METHOD_FAMILY(X) __attribute__((objc_method_family(X)))
# else
#  define SWIFT_METHOD_FAMILY(X) 
# endif
#endif
#if !defined(SWIFT_NOESCAPE)
# if __has_attribute(noescape)
#  define SWIFT_NOESCAPE __attribute__((noescape))
# else
#  define SWIFT_NOESCAPE 
# endif
#endif
#if !defined(SWIFT_RELEASES_ARGUMENT)
# if __has_attribute(ns_consumed)
#  define SWIFT_RELEASES_ARGUMENT __attribute__((ns_consumed))
# else
#  define SWIFT_RELEASES_ARGUMENT 
# endif
#endif
#if !defined(SWIFT_WARN_UNUSED_RESULT)
# if __has_attribute(warn_unused_result)
#  define SWIFT_WARN_UNUSED_RESULT __attribute__((warn_unused_result))
# else
#  define SWIFT_WARN_UNUSED_RESULT 
# endif
#endif
#if !defined(SWIFT_NORETURN)
# if __has_attribute(noreturn)
#  define SWIFT_NORETURN __attribute__((noreturn))
# else
#  define SWIFT_NORETURN 
# endif
#endif
#if !defined(SWIFT_CLASS_EXTRA)
# define SWIFT_CLASS_EXTRA 
#endif
#if !defined(SWIFT_PROTOCOL_EXTRA)
# define SWIFT_PROTOCOL_EXTRA 
#endif
#if !defined(SWIFT_ENUM_EXTRA)
# define SWIFT_ENUM_EXTRA 
#endif
#if !defined(SWIFT_CLASS)
# if __has_attribute(objc_subclassing_restricted)
#  define SWIFT_CLASS(SWIFT_NAME) SWIFT_RUNTIME_NAME(SWIFT_NAME) __attribute__((objc_subclassing_restricted)) SWIFT_CLASS_EXTRA
#  define SWIFT_CLASS_NAMED(SWIFT_NAME) __attribute__((objc_subclassing_restricted)) SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_CLASS_EXTRA
# else
#  define SWIFT_CLASS(SWIFT_NAME) SWIFT_RUNTIME_NAME(SWIFT_NAME) SWIFT_CLASS_EXTRA
#  define SWIFT_CLASS_NAMED(SWIFT_NAME) SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_CLASS_EXTRA
# endif
#endif
#if !defined(SWIFT_RESILIENT_CLASS)
# if __has_attribute(objc_class_stub)
#  define SWIFT_RESILIENT_CLASS(SWIFT_NAME) SWIFT_CLASS(SWIFT_NAME) __attribute__((objc_class_stub))
#  define SWIFT_RESILIENT_CLASS_NAMED(SWIFT_NAME) __attribute__((objc_class_stub)) SWIFT_CLASS_NAMED(SWIFT_NAME)
# else
#  define SWIFT_RESILIENT_CLASS(SWIFT_NAME) SWIFT_CLASS(SWIFT_NAME)
#  define SWIFT_RESILIENT_CLASS_NAMED(SWIFT_NAME) SWIFT_CLASS_NAMED(SWIFT_NAME)
# endif
#endif
#if !defined(SWIFT_PROTOCOL)
# define SWIFT_PROTOCOL(SWIFT_NAME) SWIFT_RUNTIME_NAME(SWIFT_NAME) SWIFT_PROTOCOL_EXTRA
# define SWIFT_PROTOCOL_NAMED(SWIFT_NAME) SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_PROTOCOL_EXTRA
#endif
#if !defined(SWIFT_EXTENSION)
# define SWIFT_EXTENSION(M) SWIFT_PASTE(M##_Swift_, __LINE__)
#endif
#if !defined(OBJC_DESIGNATED_INITIALIZER)
# if __has_attribute(objc_designated_initializer)
#  define OBJC_DESIGNATED_INITIALIZER __attribute__((objc_designated_initializer))
# else
#  define OBJC_DESIGNATED_INITIALIZER 
# endif
#endif
#if !defined(SWIFT_ENUM_ATTR)
# if __has_attribute(enum_extensibility)
#  define SWIFT_ENUM_ATTR(_extensibility) __attribute__((enum_extensibility(_extensibility)))
# else
#  define SWIFT_ENUM_ATTR(_extensibility) 
# endif
#endif
#if !defined(SWIFT_ENUM)
# define SWIFT_ENUM(_type, _name, _extensibility) enum _name : _type _name; enum SWIFT_ENUM_ATTR(_extensibility) SWIFT_ENUM_EXTRA _name : _type
# if __has_feature(generalized_swift_name)
#  define SWIFT_ENUM_NAMED(_type, _name, SWIFT_NAME, _extensibility) enum _name : _type _name SWIFT_COMPILE_NAME(SWIFT_NAME); enum SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_ENUM_ATTR(_extensibility) SWIFT_ENUM_EXTRA _name : _type
# else
#  define SWIFT_ENUM_NAMED(_type, _name, SWIFT_NAME, _extensibility) SWIFT_ENUM(_type, _name, _extensibility)
# endif
#endif
#if !defined(SWIFT_UNAVAILABLE)
# define SWIFT_UNAVAILABLE __attribute__((unavailable))
#endif
#if !defined(SWIFT_UNAVAILABLE_MSG)
# define SWIFT_UNAVAILABLE_MSG(msg) __attribute__((unavailable(msg)))
#endif
#if !defined(SWIFT_AVAILABILITY)
# define SWIFT_AVAILABILITY(plat, ...) __attribute__((availability(plat, __VA_ARGS__)))
#endif
#if !defined(SWIFT_WEAK_IMPORT)
# define SWIFT_WEAK_IMPORT __attribute__((weak_import))
#endif
#if !defined(SWIFT_DEPRECATED)
# define SWIFT_DEPRECATED __attribute__((deprecated))
#endif
#if !defined(SWIFT_DEPRECATED_MSG)
# define SWIFT_DEPRECATED_MSG(...) __attribute__((deprecated(__VA_ARGS__)))
#endif
#if !defined(SWIFT_DEPRECATED_OBJC)
# if __has_feature(attribute_diagnose_if_objc)
#  define SWIFT_DEPRECATED_OBJC(Msg) __attribute__((diagnose_if(1, Msg, "warning")))
# else
#  define SWIFT_DEPRECATED_OBJC(Msg) SWIFT_DEPRECATED_MSG(Msg)
# endif
#endif
#if defined(__OBJC__)
#if !defined(IBSegueAction)
# define IBSegueAction 
#endif
#endif
#if !defined(SWIFT_EXTERN)
# if defined(__cplusplus)
#  define SWIFT_EXTERN extern "C"
# else
#  define SWIFT_EXTERN extern
# endif
#endif
#if !defined(SWIFT_CALL)
# define SWIFT_CALL __attribute__((swiftcall))
#endif
#if !defined(SWIFT_INDIRECT_RESULT)
# define SWIFT_INDIRECT_RESULT __attribute__((swift_indirect_result))
#endif
#if !defined(SWIFT_CONTEXT)
# define SWIFT_CONTEXT __attribute__((swift_context))
#endif
#if !defined(SWIFT_ERROR_RESULT)
# define SWIFT_ERROR_RESULT __attribute__((swift_error_result))
#endif
#if defined(__cplusplus)
# define SWIFT_NOEXCEPT noexcept
#else
# define SWIFT_NOEXCEPT 
#endif
#if !defined(SWIFT_C_INLINE_THUNK)
# if __has_attribute(always_inline)
# if __has_attribute(nodebug)
#  define SWIFT_C_INLINE_THUNK inline __attribute__((always_inline)) __attribute__((nodebug))
# else
#  define SWIFT_C_INLINE_THUNK inline __attribute__((always_inline))
# endif
# else
#  define SWIFT_C_INLINE_THUNK inline
# endif
#endif
#if defined(_WIN32)
#if !defined(SWIFT_IMPORT_STDLIB_SYMBOL)
# define SWIFT_IMPORT_STDLIB_SYMBOL __declspec(dllimport)
#endif
#else
#if !defined(SWIFT_IMPORT_STDLIB_SYMBOL)
# define SWIFT_IMPORT_STDLIB_SYMBOL 
#endif
#endif
#if defined(__OBJC__)
#if __has_feature(objc_modules)
#if __has_warning("-Watimport-in-framework-header")
#pragma clang diagnostic ignored "-Watimport-in-framework-header"
#endif
@import CoreBluetooth;
@import CoreFoundation;
@import Foundation;
@import ObjectiveC;
#endif

#endif
#pragma clang diagnostic ignored "-Wproperty-attribute-mismatch"
#pragma clang diagnostic ignored "-Wduplicate-method-arg"
#if __has_warning("-Wpragma-clang-attribute")
# pragma clang diagnostic ignored "-Wpragma-clang-attribute"
#endif
#pragma clang diagnostic ignored "-Wunknown-pragmas"
#pragma clang diagnostic ignored "-Wnullability"
#pragma clang diagnostic ignored "-Wdollar-in-identifier-extension"
#pragma clang diagnostic ignored "-Wunsafe-buffer-usage"

#if __has_attribute(external_source_symbol)
# pragma push_macro("any")
# undef any
# pragma clang attribute push(__attribute__((external_source_symbol(language="Swift", defined_in="BCLRingSDK",generated_declaration))), apply_to=any(function,enum,objc_interface,objc_category,objc_protocol))
# pragma pop_macro("any")
#endif

#if defined(__OBJC__)

@class NSString;
/// 设备连接记录模型
SWIFT_CLASS("_TtC10BCLRingSDK24BCLDeviceConnectionModel")
@interface BCLDeviceConnectionModel : NSObject
/// 初始化方法
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
/// 描述信息
@property (nonatomic, readonly, copy) NSString * _Nonnull description;
@end

@class CBPeripheral;
@class NSNumber;
@class NSData;
/// 设备信息模型
SWIFT_CLASS("_TtC10BCLRingSDK18BCLDeviceInfoModel")
@interface BCLDeviceInfoModel : NSObject
/// 外设对象
@property (nonatomic, strong) CBPeripheral * _Nonnull peripheral;
/// 外设的名称
@property (nonatomic, readonly, copy) NSString * _Nullable peripheralName;
/// 外设的名称（广播协议中 kCBAdvDataLocalName的值）
@property (nonatomic, readonly, copy) NSString * _Nullable localName;
/// 外设的UUID
@property (nonatomic, readonly, copy) NSString * _Nonnull uuidString;
/// 外设的MAC地址
@property (nonatomic, copy) NSString * _Nullable macAddress;
/// 外设的RSSI值
@property (nonatomic, strong) NSNumber * _Nullable rssi;
/// 设备在扫描阶段是否已经被检索到并且是连接状态
@property (nonatomic) BOOL isScannedAndConnected;
/// 外设的广播数据
@property (nonatomic, copy) NSDictionary<NSString *, id> * _Nullable advertisementData;
/// 外设的广播数据中的制造商数据
@property (nonatomic, readonly, copy) NSData * _Nonnull advDataManufacturerData;
/// 是否支持二代协议:0、不支持，1、支持，2、分段记步（支持二代协议，且记步方式为分段记步模式）
@property (nonatomic, readonly) NSInteger communicationProtocolVersion;
/// 是否支持绑定：0、不支持绑定、配对(仅软连接)，1、绑定和配对，2、仅支持配对
@property (nonatomic, readonly) NSInteger bindingIndicatorBit;
/// 充电指示位：0、代表未充电，1、代表充电中,2、代表充电完成
@property (nonatomic, readonly) NSInteger chargingIndicator;
/// phy固件的bootMode模式（phy固件升级中断导致设备没有退出boot模式，戒指表现为：名称包含PPlusota信息，且mac地址在原地址上+1）
@property (nonatomic) BOOL isPhyBootMode;
/// 初始化方法
- (nonnull instancetype)initWithPeripheral:(CBPeripheral * _Nonnull)peripheral peripheralName:(NSString * _Nullable)peripheralName rssi:(NSNumber * _Nullable)rssi macAddress:(NSString * _Nullable)macAddress advertisementData:(NSDictionary<NSString *, id> * _Nullable)advertisementData isScannedAndConnected:(BOOL)isScannedAndConnected isphyBootMode:(BOOL)isphyBootMode OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end

/// 手势HID模式枚举
typedef SWIFT_ENUM(uint8_t, BCLGestureHIDMode, open) {
/// 刷视频模式
  BCLGestureHIDModeVideoMode = 0,
/// 拍照模式
  BCLGestureHIDModePhotoMode = 1,
/// 音乐模式
  BCLGestureHIDModeMusicMode = 2,
/// PPT模式
  BCLGestureHIDModePptMode = 3,
/// 打响指(拍照)模式
  BCLGestureHIDModeSnapPhotoMode = 4,
/// 关闭
  BCLGestureHIDModeDisabled = 0xFF,
};

/// OTA类型
typedef SWIFT_ENUM(uint8_t, BCLOTAType, open) {
/// 未知
  BCLOTATypeUnknown = 0,
/// 阿波罗
  BCLOTATypeApollo = 1,
/// Nordic
  BCLOTATypeNordic = 2,
/// Phy
  BCLOTATypePhy = 3,
};

/// 戒指数据库模型
SWIFT_CLASS("_TtC10BCLRingSDK14BCLRingDBModel")
@interface BCLRingDBModel : NSObject
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)initWithBytes:(NSArray<NSNumber *> * _Nonnull)bytes OBJC_DESIGNATED_INITIALIZER;
/// 将对象转换为字典
- (NSDictionary<NSString *, id> * _Nonnull)toDictionary SWIFT_WARN_UNUSED_RESULT;
@end

SWIFT_CLASS("_TtC10BCLRingSDK22BCLRingLocalSleepModel")
@interface BCLRingLocalSleepModel : NSObject
/// 零星睡眠小时
@property (nonatomic) NSInteger hours;
/// 零星睡眠分钟
@property (nonatomic) NSInteger minutes;
/// 全部睡眠小时
@property (nonatomic) NSInteger allHours;
/// 全部睡眠分钟
@property (nonatomic) NSInteger allMinutes;
/// 睡眠小时
@property (nonatomic) NSInteger sleepHours;
/// 睡眠分钟
@property (nonatomic) NSInteger sleepMinutes;
/// 深度睡眠时间
@property (nonatomic) int64_t highTime;
/// 浅度睡眠时间
@property (nonatomic) int64_t lowTime;
/// 眼动时间
@property (nonatomic) int64_t ydTime;
/// 清醒时间
@property (nonatomic) int64_t qxTime;
/// 入睡时间戳
@property (nonatomic) int64_t startTime;
/// 清醒时间戳
@property (nonatomic) int64_t endTime;
/// 睡眠数据
@property (nonatomic, copy) NSArray<BCLRingDBModel *> * _Nonnull sleepDataList;
@property (nonatomic, readonly, copy) NSString * _Nonnull description;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end

/// 蓝牙管理类
SWIFT_CLASS("_TtC10BCLRingSDK14BCLRingManager")
@interface BCLRingManager : NSObject
/// 单例对象
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, strong) BCLRingManager * _Nonnull shared;)
+ (BCLRingManager * _Nonnull)shared SWIFT_WARN_UNUSED_RESULT;
/// 初始化
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end

/// 网络访问地址配置枚举
typedef SWIFT_ENUM(NSInteger, NetworkRegion, open) {
  NetworkRegionDomestic = 0,
  NetworkRegionOverseas = 1,
};

@class CBCentralManager;
@interface BCLRingManager (SWIFT_EXTENSION(BCLRingSDK)) <CBCentralManagerDelegate>
/// 蓝牙状态更新
/// \param central 中心设备
///
- (void)centralManagerDidUpdateState:(CBCentralManager * _Nonnull)central;
/// 蓝牙设备连接成功
/// \param central 中心设备
///
/// \param peripheral 外设
///
- (void)centralManager:(CBCentralManager * _Nonnull)central didConnectPeripheral:(CBPeripheral * _Nonnull)peripheral;
/// 蓝牙设备恢复连接状态
/// \param central 中心设备
///
/// \param dict 
///
- (void)centralManager:(CBCentralManager * _Nonnull)central willRestoreState:(NSDictionary<NSString *, id> * _Nonnull)dict;
/// 蓝牙设备连接失败
/// <ul>
///   <li>
///     Parameters:
///   </li>
///   <li>
///     central: 中心设备
///   </li>
///   <li>
///     peripheral:  外设
///   </li>
///   <li>
///     error:  错误信息
///   </li>
/// </ul>
- (void)centralManager:(CBCentralManager * _Nonnull)central didFailToConnectPeripheral:(CBPeripheral * _Nonnull)peripheral error:(NSError * _Nullable)error;
/// 蓝牙设备断开连接
/// \param central 中心设备
///
/// \param peripheral 外设
///
/// \param error 错误信息
///
- (void)centralManager:(CBCentralManager * _Nonnull)central didDisconnectPeripheral:(CBPeripheral * _Nonnull)peripheral error:(NSError * _Nullable)error;
/// 扫描外设回调
/// <ul>
///   <li>
///     Parameters:
///   </li>
///   <li>
///     central: 中心设备
///   </li>
///   <li>
///     peripheral:  外设
///   </li>
///   <li>
///     advertisementData:  广播数据
///   </li>
///   <li>
///     RSSI:  信号强度
///   </li>
/// </ul>
- (void)centralManager:(CBCentralManager * _Nonnull)central didDiscoverPeripheral:(CBPeripheral * _Nonnull)peripheral advertisementData:(NSDictionary<NSString *, id> * _Nonnull)advertisementData RSSI:(NSNumber * _Nonnull)RSSI;
/// 扫描外设断开连接回调(需要再连接时候添加CBConnectPeripheralOptionEnableAutoReconnect: true项，但是需要iOS17以上系统支持)
/// \param central 中心设备
///
/// \param peripheral 外设
///
/// \param timestamp 断开连接时间戳
///
/// \param isReconnecting 是否正在重新连接
///
/// \param error 错误信息
///
- (void)centralManager:(CBCentralManager * _Nonnull)central didDisconnectPeripheral:(CBPeripheral * _Nonnull)peripheral timestamp:(CFAbsoluteTime)timestamp isReconnecting:(BOOL)isReconnecting error:(NSError * _Nullable)error;
@end

@class CBService;
@class CBCharacteristic;
@class CBDescriptor;
@class CBL2CAPChannel;
@interface BCLRingManager (SWIFT_EXTENSION(BCLRingSDK)) <CBPeripheralDelegate>
/// 外设名称更新
/// \param peripheral 外设
///
- (void)peripheralDidUpdateName:(CBPeripheral * _Nonnull)peripheral;
/// 外设的 RSSI 值读取结果
/// \param peripheral 外设
///
/// \param RSSI 外设的 RSSI 值
///
/// \param error 错误信息，如果发生错误
///
- (void)peripheral:(CBPeripheral * _Nonnull)peripheral didReadRSSI:(NSNumber * _Nonnull)RSSI error:(NSError * _Nullable)error;
/// 外设服务发现
/// \param peripheral 外设
///
/// \param error 错误信息，如果发生错误
///
- (void)peripheral:(CBPeripheral * _Nonnull)peripheral didDiscoverServices:(NSError * _Nullable)error;
/// 外设服务修改
/// \param peripheral 外设
///
/// \param invalidatedServices 已失效的服务列表
///
- (void)peripheral:(CBPeripheral * _Nonnull)peripheral didModifyServices:(NSArray<CBService *> * _Nonnull)invalidatedServices;
/// 外设服务特征发现
/// \param peripheral 外设
///
/// \param service 外设的服务对象
///
/// \param error 错误信息，如果发生错误
///
- (void)peripheral:(CBPeripheral * _Nonnull)peripheral didDiscoverCharacteristicsForService:(CBService * _Nonnull)service error:(NSError * _Nullable)error;
/// 外设特征值数据回调
/// \param peripheral 外设
///
/// \param characteristic 外设的特征对象
///
/// \param error 错误信息，如果发生错误
///
- (void)peripheral:(CBPeripheral * _Nonnull)peripheral didUpdateValueForCharacteristic:(CBCharacteristic * _Nonnull)characteristic error:(NSError * _Nullable)error;
/// 外设特征值写入结果
/// \param peripheral 外设
///
/// \param characteristic 外设的特征对象
///
/// \param error 错误信息，如果发生错误
///
- (void)peripheral:(CBPeripheral * _Nonnull)peripheral didWriteValueForCharacteristic:(CBCharacteristic * _Nonnull)characteristic error:(NSError * _Nullable)error;
/// 外设特征的通知状态更新
/// \param peripheral 外设
///
/// \param characteristic 外设的特征对象
///
/// \param error 错误信息，如果发生错误
///
- (void)peripheral:(CBPeripheral * _Nonnull)peripheral didUpdateNotificationStateForCharacteristic:(CBCharacteristic * _Nonnull)characteristic error:(NSError * _Nullable)error;
/// 外设描述符写入结果
/// \param peripheral 外设
///
/// \param descriptor 外设的描述符对象
///
/// \param error 错误信息，如果发生错误
///
- (void)peripheral:(CBPeripheral * _Nonnull)peripheral didWriteValueForDescriptor:(CBDescriptor * _Nonnull)descriptor error:(NSError * _Nullable)error;
/// 外设描述符值更新
/// \param peripheral 外设
///
/// \param descriptor 外设的描述符对象
///
/// \param error 错误信息，如果发生错误
///
- (void)peripheral:(CBPeripheral * _Nonnull)peripheral didUpdateValueForDescriptor:(CBDescriptor * _Nonnull)descriptor error:(NSError * _Nullable)error;
/// 外设特征描述符发现
/// \param peripheral 外设
///
/// \param characteristic 外设的特征对象
///
/// \param error 错误信息，如果发生错误
///
- (void)peripheral:(CBPeripheral * _Nonnull)peripheral didDiscoverDescriptorsForCharacteristic:(CBCharacteristic * _Nonnull)characteristic error:(NSError * _Nullable)error;
/// 外设L2CAP通道打开
/// \param peripheral 外设
///
/// \param channel 打开的L2CAP通道
///
/// \param error 错误信息，如果发生错误
///
- (void)peripheral:(CBPeripheral * _Nonnull)peripheral didOpenL2CAPChannel:(CBL2CAPChannel * _Nullable)channel error:(NSError * _Nullable)error;
/// 外设服务的嵌套服务发现
/// \param peripheral 外设
///
/// \param service 外设的服务对象
///
/// \param error 错误信息，如果发生错误
///
- (void)peripheral:(CBPeripheral * _Nonnull)peripheral didDiscoverIncludedServicesForService:(CBService * _Nonnull)service error:(NSError * _Nullable)error;
@end

SWIFT_CLASS("_TtC10BCLRingSDK20BCLRingSleepDayModel")
@interface BCLRingSleepDayModel : NSObject
@end

/// 睡眠模型
SWIFT_CLASS("_TtC10BCLRingSDK17BCLRingSleepModel")
@interface BCLRingSleepModel : NSObject
/// 睡眠时长（小时）
@property (nonatomic) NSInteger hours;
/// 睡眠时长（分钟）
@property (nonatomic) NSInteger minutes;
/// 睡眠总时长（秒）
@property (nonatomic) int64_t sleepTime;
/// 深度睡眠时间
@property (nonatomic) int64_t deepTime;
/// 浅度睡眠时间
@property (nonatomic) int64_t lowTime;
/// 眼动时间
@property (nonatomic) int64_t ydTime;
/// 清醒时间
@property (nonatomic) int64_t qxTime;
/// 入睡时间戳
@property (nonatomic) int64_t startTime;
/// 清醒时间戳
@property (nonatomic) int64_t endTime;
/// 睡眠效率
@property (nonatomic) double xiaolv;
/// 深睡比例
@property (nonatomic) double shenshui;
/// 睡眠得分
@property (nonatomic) NSInteger score;
/// 清醒次数
@property (nonatomic) NSInteger wakeupCount;
/// 睡眠数据类型
@property (nonatomic) NSInteger sleepDataType;
/// 睡眠数据列表
@property (nonatomic, copy) NSArray<BCLRingDBModel *> * _Nonnull sleepDataList;
@property (nonatomic, readonly, copy) NSString * _Nonnull description;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end

/// 时区枚举
typedef SWIFT_ENUM(NSInteger, BCLRingTimeZone, open) {
/// 中时区
  BCLRingTimeZoneUTC = 0x00,
/// 东一区
  BCLRingTimeZoneEast1 = 0x01,
/// 东二区
  BCLRingTimeZoneEast2 = 0x02,
/// 东三区
  BCLRingTimeZoneEast3 = 0x03,
/// 东四区
  BCLRingTimeZoneEast4 = 0x04,
/// 东五区
  BCLRingTimeZoneEast5 = 0x05,
/// 东六区
  BCLRingTimeZoneEast6 = 0x06,
/// 东七区
  BCLRingTimeZoneEast7 = 0x07,
/// 东八区
  BCLRingTimeZoneEast8 = 0x08,
/// 东九区
  BCLRingTimeZoneEast9 = 0x09,
/// 东十区
  BCLRingTimeZoneEast10 = 0x0A,
/// 东十一区
  BCLRingTimeZoneEast11 = 0x0B,
/// 东十二区
  BCLRingTimeZoneEast12 = 0x0C,
/// 西十二区
  BCLRingTimeZoneWest12 = 0xF4,
/// 西十一区
  BCLRingTimeZoneWest11 = 0xF5,
/// 西十区
  BCLRingTimeZoneWest10 = 0xF6,
/// 西九区
  BCLRingTimeZoneWest9 = 0xF7,
/// 西八区
  BCLRingTimeZoneWest8 = 0xF8,
/// 西七区
  BCLRingTimeZoneWest7 = 0xF9,
/// 西六区
  BCLRingTimeZoneWest6 = 0xFA,
/// 西五区
  BCLRingTimeZoneWest5 = 0xFB,
/// 西四区
  BCLRingTimeZoneWest4 = 0xFC,
/// 西三区
  BCLRingTimeZoneWest3 = 0xFD,
/// 西二区
  BCLRingTimeZoneWest2 = 0xFE,
/// 西一区
  BCLRingTimeZoneWest1 = 0xFF,
};

typedef SWIFT_ENUM(uint8_t, BCLTouchHIDMode, open) {
/// 刷视频模式
  BCLTouchHIDModeVideoMode = 0,
/// 拍照模式
  BCLTouchHIDModePhotoMode = 1,
/// 音乐模式
  BCLTouchHIDModeMusicMode = 2,
/// PPT模式
  BCLTouchHIDModePptMode = 3,
/// 上传实时音频
  BCLTouchHIDModeAudioUploadMode = 4,
/// 关闭
  BCLTouchHIDModeDisabled = 0xFF,
};

#endif
#if __has_attribute(external_source_symbol)
# pragma clang attribute pop
#endif
#if defined(__cplusplus)
#endif
#pragma clang diagnostic pop
#endif

#else
#error unsupported Swift architecture
#endif
